/**
 * The cheat sheet webview.
 *
 * A single reusable panel: opening it again reveals the existing one rather than
 * stacking tabs. The markup is generated by `src/cheatsheet/render.ts`, which
 * knows nothing about VS Code; this file only owns the panel's lifecycle and the
 * content security policy nonce.
 */

import { randomBytes } from "node:crypto";
import * as vscode from "vscode";
import { renderCheatSheet } from "../cheatsheet/render";

export class CheatSheetPanel implements vscode.Disposable {
  #panel: vscode.WebviewPanel | undefined;

  openOrReveal(): void {
    if (this.#panel !== undefined) {
      this.#panel.reveal(vscode.ViewColumn.Active);
      return;
    }

    const panel = vscode.window.createWebviewPanel(
      "paredit-redex.cheatSheet",
      "Paredit Cheat Sheet",
      vscode.ViewColumn.Active,
      { enableScripts: true, retainContextWhenHidden: true },
    );
    panel.webview.html = renderCheatSheet(nonce());
    panel.onDidDispose(() => {
      this.#panel = undefined;
    });
    this.#panel = panel;
  }

  dispose(): void {
    this.#panel?.dispose();
    this.#panel = undefined;
  }
}

/**
 * A fresh nonce per panel, so the CSP can admit exactly our own style and script.
 *
 * It gates what the webview will execute, so it comes from the cryptographic
 * generator rather than `Math.random`.
 */
function nonce(): string {
  return randomBytes(16).toString("base64url");
}
