/**
 * Renders the cheat sheet to a self-contained HTML document.
 *
 * Pure: no `vscode` import, so the markup is unit-testable. Colours come from
 * the editor's own theme variables rather than a palette of our own, so the page
 * matches whatever theme the reader is using.
 */

import { CARET } from "../ops/caret-notation";
import type { CatalogEntry, EntryGroup } from "./catalog";
import { CATALOG } from "./catalog";
import { exampleFor } from "./examples";

const GROUP_ORDER: readonly EntryGroup[] = ["Navigate", "Depth", "Kill", "Rearrange", "Help"];

const GROUP_BLURB: Readonly<Record<EntryGroup, string>> = {
  Navigate: "Move by structure instead of by character. Nothing here changes the text.",
  Depth: "Change how deeply nested something is — the heart of paredit.",
  Kill: "Delete whole data, so the brackets always stay balanced.",
  Rearrange: "Reorder and regroup siblings within a list.",
  Help: "",
};

export function escapeHtml(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/** Render a caret-marked snippet, showing the caret as a cursor rather than a glyph. */
export function renderSnippet(marked: string): string {
  const [before = "", after = ""] = marked.split(CARET);
  return `${escapeHtml(before)}<span class="caret"></span>${escapeHtml(after)}`;
}

/** Render one key chord as a run of `kbd` elements. */
export function renderKeys(key: string): string {
  return key
    .split("+")
    .map((part) => `<kbd>${escapeHtml(KEY_LABELS[part] ?? part)}</kbd>`)
    .join("<span class=\"plus\">+</span>");
}

const KEY_LABELS: Readonly<Record<string, string>> = {
  ctrl: "Ctrl",
  alt: "Alt",
  shift: "Shift",
  up: "↑",
  down: "↓",
  left: "←",
  right: "→",
  backspace: "Backspace",
};

function keyCell(entry: CatalogEntry): string {
  if (entry.keys.length === 0) {
    return '<span class="unbound">command palette</span>';
  }
  return entry.keys.map(renderKeys).join('<span class="alt-key">or</span>');
}

function quickRow(entry: CatalogEntry): string {
  return `<tr>
      <td class="keys">${keyCell(entry)}</td>
      <td class="name">${escapeHtml(entry.title)}</td>
      <td class="summary">${escapeHtml(entry.summary)}</td>
    </tr>`;
}

function quickReference(): string {
  return GROUP_ORDER.map((group) => {
    const entries = CATALOG.filter((entry) => entry.group === group);
    if (entries.length === 0) {
      return "";
    }
    return `<section class="group" data-group="${escapeHtml(group)}">
      <h2>${escapeHtml(group)}</h2>
      ${GROUP_BLURB[group] === "" ? "" : `<p class="blurb">${escapeHtml(GROUP_BLURB[group])}</p>`}
      <table>${entries.map((entry) => quickRow(entry)).join("")}</table>
    </section>`;
  }).join("");
}

function guideCard(entry: CatalogEntry): string {
  const example = exampleFor(entry);
  const demo =
    example === undefined
      ? ""
      : `<div class="demo">
          <div class="pane"><span class="label">before</span><code>${renderSnippet(example.before)}</code></div>
          <div class="arrow" aria-hidden="true">→</div>
          <div class="pane"><span class="label">after</span><code>${renderSnippet(example.after)}</code></div>
        </div>`;

  return `<article class="card" data-search="${escapeHtml(
    `${entry.title} ${entry.summary} ${entry.detail} ${entry.keys.join(" ")}`.toLowerCase(),
  )}">
      <header>
        <h3>${escapeHtml(entry.title)}</h3>
        <div class="keys">${keyCell(entry)}</div>
      </header>
      <p class="detail">${escapeHtml(entry.detail)}</p>
      ${demo}
    </article>`;
}

function guide(): string {
  return GROUP_ORDER.map((group) => {
    const entries = CATALOG.filter((entry) => entry.group === group);
    if (entries.length === 0) {
      return "";
    }
    return `<section class="group" data-group="${escapeHtml(group)}">
      <h2>${escapeHtml(group)}</h2>
      ${GROUP_BLURB[group] === "" ? "" : `<p class="blurb">${escapeHtml(GROUP_BLURB[group])}</p>`}
      ${entries.map((entry) => guideCard(entry)).join("")}
    </section>`;
  }).join("");
}

/**
 * The whole page.
 *
 * `nonce` is required by the webview's content security policy; the caller
 * generates a fresh one per panel.
 */
export function renderCheatSheet(nonce: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';">
<title>Paredit Cheat Sheet</title>
<style nonce="${nonce}">${STYLES}</style>
</head>
<body>
<header class="top">
  <div class="titles">
    <h1>Paredit for Racket</h1>
    <p class="sub">Every example below is generated by running the command, so it shows what this build actually does.</p>
  </div>
  <div class="controls">
    <div class="segmented" role="tablist">
      <button id="tab-quick" role="tab" aria-selected="true" class="active">Quick reference</button>
      <button id="tab-guide" role="tab" aria-selected="false">Guide</button>
    </div>
    <input id="filter" type="search" placeholder="Filter commands…" aria-label="Filter commands">
  </div>
</header>

<main>
  <div id="view-quick">${quickReference()}</div>
  <div id="view-guide" hidden>${guide()}</div>
  <p id="empty" hidden class="empty">No command matches that.</p>
</main>

<footer>
  <p>The bracket chords assume a US layout: <kbd>Ctrl</kbd><span class="plus">+</span><kbd>Shift</kbd><span class="plus">+</span><kbd>0</kbd> is where <code>)</code> lives there. The <kbd>Ctrl</kbd><span class="plus">+</span><kbd>←</kbd> / <kbd>→</kbd> alternates for slurp and barf are layout-independent. Rebind anything in <code>keybindings.json</code>.</p>
</footer>

<script nonce="${nonce}">${SCRIPT}</script>
</body>
</html>`;
}

const STYLES = `
/*
 * Colours come from the editor's theme. The --fallback-* layer underneath is
 * what makes the page legible anywhere else — opening the generated HTML in a
 * browser to check the layout, for one.
 */
:root {
  color-scheme: light dark;
  --fallback-fg: #1f2328;
  --fallback-bg: #ffffff;
  --fallback-line: rgba(31, 35, 40, 0.18);
  --fallback-surface: rgba(31, 35, 40, 0.06);
}
@media (prefers-color-scheme: dark) {
  :root {
    --fallback-fg: #e6e6e6;
    --fallback-bg: #1e1e1e;
    --fallback-line: rgba(230, 230, 230, 0.2);
    --fallback-surface: rgba(230, 230, 230, 0.08);
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 0 2rem 3rem;
  font-family: var(--vscode-font-family, system-ui, sans-serif);
  font-size: var(--vscode-font-size, 13px);
  color: var(--vscode-foreground, var(--fallback-fg));
  background: var(--vscode-editor-background, var(--fallback-bg));
  line-height: 1.55;
}
code, kbd, .snippet { font-family: var(--vscode-editor-font-family, ui-monospace, monospace); }

.top {
  position: sticky; top: 0; z-index: 2;
  display: flex; flex-wrap: wrap; gap: 1rem 2rem;
  align-items: flex-end; justify-content: space-between;
  padding: 1.75rem 0 1rem;
  background: var(--vscode-editor-background, var(--fallback-bg));
  border-bottom: 1px solid var(--vscode-panel-border, var(--fallback-line));
}
h1 { margin: 0; font-size: 1.5rem; font-weight: 600; letter-spacing: -0.01em; }
.sub { margin: 0.35rem 0 0; max-width: 52ch; opacity: 0.75; }
.controls { display: flex; gap: 0.75rem; align-items: center; }

.segmented { display: inline-flex; border: 1px solid var(--vscode-panel-border, var(--fallback-line)); border-radius: 6px; overflow: hidden; }
.segmented button {
  appearance: none; border: 0; cursor: pointer;
  padding: 0.4rem 0.9rem; font: inherit;
  background: transparent; color: var(--vscode-foreground, var(--fallback-fg));
}
.segmented button.active {
  background: var(--vscode-button-background, var(--fallback-surface));
  color: var(--vscode-button-foreground, inherit);
}
#filter {
  padding: 0.4rem 0.6rem; font: inherit; min-width: 16ch;
  color: var(--vscode-input-foreground, var(--fallback-fg));
  background: var(--vscode-input-background, transparent);
  border: 1px solid var(--vscode-input-border, var(--vscode-panel-border, var(--fallback-line)));
  border-radius: 6px;
}

.group { margin: 2rem 0 0; }
.group h2 { margin: 0 0 0.15rem; font-size: 0.78rem; font-weight: 700; letter-spacing: 0.09em; text-transform: uppercase; opacity: 0.6; }
.blurb { margin: 0 0 0.9rem; opacity: 0.75; max-width: 62ch; }

table { border-collapse: collapse; width: 100%; max-width: 62rem; }
tr { border-bottom: 1px solid var(--vscode-panel-border, var(--fallback-line)); }
tr:last-child { border-bottom: 0; }
td { padding: 0.42rem 1rem 0.42rem 0; vertical-align: baseline; }
td.keys { white-space: nowrap; width: 1%; }
td.name { font-weight: 600; white-space: nowrap; width: 1%; }
td.summary { opacity: 0.8; }

kbd {
  display: inline-block; padding: 0.05rem 0.4rem; min-width: 1.6em; text-align: center;
  font-size: 0.85em; line-height: 1.5;
  border: 1px solid var(--vscode-panel-border, var(--fallback-line));
  border-bottom-width: 2px; border-radius: 4px;
  background: var(--vscode-editorWidget-background, var(--fallback-surface));
}
.plus { opacity: 0.4; padding: 0 0.15rem; font-size: 0.8em; }
.alt-key { opacity: 0.5; padding: 0 0.5rem; font-size: 0.85em; font-style: italic; }
.unbound { opacity: 0.55; font-style: italic; }

.card {
  max-width: 62rem;
  padding: 1rem 0 1.1rem;
  border-bottom: 1px solid var(--vscode-panel-border, var(--fallback-line));
}
.card header { display: flex; flex-wrap: wrap; gap: 0.5rem 1rem; align-items: baseline; }
.card h3 { margin: 0; font-size: 1rem; font-weight: 600; }
.detail { margin: 0.4rem 0 0; max-width: 68ch; opacity: 0.85; }

.demo { display: flex; flex-wrap: wrap; align-items: stretch; gap: 0.75rem; margin-top: 0.85rem; }
.pane {
  display: flex; flex-direction: column; gap: 0.3rem;
  padding: 0.6rem 0.8rem; border-radius: 6px;
  background: var(--vscode-textCodeBlock-background, var(--fallback-surface));
  border: 1px solid var(--vscode-panel-border, var(--fallback-line));
  overflow-x: auto;
}
.pane .label { font-size: 0.68rem; letter-spacing: 0.1em; text-transform: uppercase; opacity: 0.5; }
.pane code { white-space: pre; font-size: 0.95em; }
.arrow { align-self: center; opacity: 0.45; font-size: 1.1rem; }

.caret {
  display: inline-block; width: 2px; height: 1.05em; vertical-align: text-bottom;
  margin: 0 -1px; border-radius: 1px;
  background: var(--vscode-editorCursor-foreground, currentColor);
}

.empty { margin: 3rem 0; opacity: 0.6; }
footer { margin-top: 3rem; padding-top: 1rem; max-width: 62rem; border-top: 1px solid var(--vscode-panel-border, var(--fallback-line)); opacity: 0.7; }
footer p { margin: 0; }
`;

const SCRIPT = `
const quickTab = document.getElementById('tab-quick');
const guideTab = document.getElementById('tab-guide');
const quickView = document.getElementById('view-quick');
const guideView = document.getElementById('view-guide');
const filter = document.getElementById('filter');
const empty = document.getElementById('empty');

function show(which) {
  const quick = which === 'quick';
  quickView.hidden = !quick;
  guideView.hidden = quick;
  quickTab.classList.toggle('active', quick);
  guideTab.classList.toggle('active', !quick);
  quickTab.setAttribute('aria-selected', String(quick));
  guideTab.setAttribute('aria-selected', String(!quick));
  applyFilter();
}

quickTab.addEventListener('click', () => { show('quick'); });
guideTab.addEventListener('click', () => { show('guide'); });

function applyFilter() {
  const needle = filter.value.trim().toLowerCase();
  const view = quickView.hidden ? guideView : quickView;
  let visible = 0;

  for (const row of view.querySelectorAll('tr')) {
    const match = needle === '' || row.textContent.toLowerCase().includes(needle);
    row.hidden = !match;
    if (match) visible += 1;
  }
  for (const card of view.querySelectorAll('.card')) {
    const match = needle === '' || card.dataset.search.includes(needle);
    card.hidden = !match;
    if (match) visible += 1;
  }
  for (const group of view.querySelectorAll('.group')) {
    const rows = [...group.querySelectorAll('tr, .card')];
    group.hidden = rows.length > 0 && rows.every((node) => node.hidden);
  }
  empty.hidden = visible > 0;
}

filter.addEventListener('input', applyFilter);
`;
